version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

# commands:
#   destroy-environment:
#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
#     ...

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...

jobs:
  build-frontend:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: cd /home/circleci/project/frontend && npm install
      - run:
          name: Build
          command: cd /home/circleci/project/frontend && npm run build:prod

  build-backend:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: cd /home/circleci/project/backend && npm install
      - run:
          name: Build
          command: cd /home/circleci/project/backend && npm run build

  test-frontend:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: cd /home/circleci/project/frontend && npm install
      - run:
          name: Test
          command: cd /home/circleci/project/frontend && npm run test

  test-backend:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: cd /home/circleci/project/backend && npm install
      - run:
          name: Test
          command: cd /home/circleci/project/backend && npm run test

  scan-frontend:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: cd /home/circleci/project/frontend && npm install
      - run:
          name: Audit NPM Dependencies
          command: cd /home/circleci/project/frontend && npm audit --audit-level=critical

  scan-backend:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: cd /home/circleci/project/backend && npm install
      - run:
          name: Audit NPM Dependencies
          command: cd /home/circleci/project/backend && npm audit --audit-level=critical

#  deploy-infrastructure:

#  configure-infrastructure:

#  run-migrations:

#  deploy-frontend:

#  deploy-backend:

#  smoke-test:

#  cloudfront-update:

workflows:
  integration:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            - build-frontend
      - test-backend:
          requires:
            - build-backend
      - scan-frontend:
          requires:
            - test-frontend
      - scan-backend:
          requires:
            - test-backend
